### ISSUE TITLE
Storage of Noise Profiles

### ISSUE THREAD

**Issue by borgdylan** [lucianodato/noise-repellent#49] opened 2018-01-01 09:48 UTC
Would it be possible for the plugin to be able to save the noise profiles to disk, so they could be reloaded in future sessions. I tried using the plugin in ardour, and when I close and reopened the project the noise profile got lost.

**Comment by lucianodato** [comment] 2018-01-01 15:23
That shouldn't be the default behavior. This is a bug. By the way what version of Ardour are you using?

**Comment by lucianodato** [comment] 2018-01-01 15:29
A basic one, but are you using the latest version of the plugin?

**Comment by borgdylan** [comment] 2018-01-01 16:09
I am using ardour 5.12 manually compiled from git.

**Comment by borgdylan** [comment] 2018-01-01 16:10
I have also compiled the plugin from the master branch.

**Comment by lucianodato** [comment] 2018-01-01 16:15
Ok I will check asap. Thanks for reporting.

**Comment by lucianodato** [comment] 2018-01-02 03:04
Indeed I can replicate the bug. I will fix it as soon as I can. Sorry for the inconvenience I'm now getting back to work on the plugin after a long period of inactivity.

**Comment by borgdylan** [comment] 2018-01-02 06:15
Thanks. I came across it as I was trying to find something better than using the Calf Equalizer for removing noise. EQ can be too destructive for certain cases.

**Comment by lucianodato** [comment] 2018-01-02 22:28
You can try now again. It's fixed in Mixbus 4.3 and Ardour 5.12 in my machine. Tell me how it goes for you.

**Comment by borgdylan** [comment] 2018-01-13 12:29
I have tested again on a project I was working on. The profile seesm to still be lost. The project was started after updating noise-repellent on my machine.

**Comment by borgdylan** [comment] 2018-01-13 12:30
Ardour seems to be saving LV2 state only, I cannot see any separate file under the plugins directory with noise-repellent data.

**Comment by borgdylan** [comment] 2018-01-13 12:33
Also remeber that for ardour to save LV2 state, it must be mentioned in the manifest files along with other parameters if you are going the route of adding the profile as an LV2 parameters rather than a separate on -disk file.

**Comment by lucianodato** [comment] 2018-01-13 13:19
Yeah it is implemented as an lv2 state. Was working right with ardour 5.11. In fact lots of users tested that feature successfully. I might have changed something during my latest commits. I will take a look. The weird thing is that is working here. I will inform you when I have something.

**Comment by Efenstor** [comment] 2018-03-11 19:37
Luciano, your plugin is _incredible_! It definitely surpasses the commercial solutions from Izotope and WaveArts! The only source of sorrow is this bug.

Yes, I can confirm, it does not save the noise profile with the latest stable Ardour 5.12 (official binaries for Linux x64). Sometimes it saves the profile, sometimes it does not. I mean, if I have, say, 5 tracks with Noise Repellent, there's a big change that only 2 of them will have the profile saved.

**Comment by lucianodato** [comment] 2018-03-12 19:38
I hadn't have much time to work on this lately. It seems that this is a difficult one. I'm sorry for the inconvenience I will get back to it ASAP.

**Comment by Efenstor** [comment] 2018-03-13 10:28
A couple of things I have noticed about the "plugins" dir behavior:

1. Each time I save the project the number of saved states increases for each track. Is that normal? I see that "state1" still has the FFT data inside, while all the rest already has zeros. At some point the earlier states are erased, and thus the FFT data becomes lost completely.

2. When I insert the plugin into 8 stereo tracks, two instances are created for each track ((2x1) Noise Repellent), but in the "plugins" I see only 8 subdirs, while logically there should be 16 states saved somewhere. May be I'm wrong, since the 2 instances are always identical and possibly treated as a single plugin.

**Comment by lucianodato** [comment] 2018-03-13 22:37
Hi Efenstor, thanks for your detailed comments. 
1. Every time you save a state will be saved for each plugin instance. I think that this is the way the lv2 state extension work. I don't know how many states the host will keep that's something that is not implemented in my code but in Ardour itself.
2. This might be another bug altogether. I have never tried noise-repellent on stereo tracks. Will report soon on this one.
3. Well if you don't capture any noise profile the information that will store will be all zeros. Indeed it was an overflow. Well spotted. I have tried to fix that in my latest commit. Could you try now and report back? Maybe it's fixed now.

**Comment by Efenstor** [comment] 2018-03-14 13:03
Believe it or not, this small fix solved _all_ the issues! Now it's even there are 8 plugin dirs for 4 stereo tracks.

**Comment by Efenstor** [comment] 2018-03-14 13:06
Now I can finally carry on with my project (remastering of my old demo album). Thank you very much, Luciano!

**Comment by lucianodato** [comment] 2018-03-14 13:22
Finally! Great news! Thanks for your help Efenstor! This might deserve a new release.

**Comment by Efenstor** [comment] 2018-03-14 13:24
One more thing: it's recommended to clean up the "plugins" dir manually and re-train Noise Repellent for existing projects.

**Comment by Efenstor** [comment] 2018-03-14 13:42
I was wrong about the number of tracks for stereo tracks, it's not doubled as probably should, so this shall require a bit more clarification, I mean how Noise Repellent works with stereo tracks, in the two-instanced mode. But the profiles are now saved and restored correctly and there are no excessive saved states.

**Comment by Efenstor** [comment] 2018-03-14 13:48
I think I already got it: Ardour creates a separate state dir, not a plugin dir for multi-instance plugins. So for each stereo track two state files are written or read. So I guess Noise Repellent works fine with the stereo tracks out of the box.

**Comment by lucianodato** [comment] 2018-03-14 14:08
That's an Ardour feature. I have tried with a stereo track and obtained what you mention. Great, less work for me!

**Closed** 2018-03-14 15:09 UTC
Labels: bug, work in progress

**Comment by davidhealey** [comment] 2019-09-05 11:29
Noise profiles are being reset when reloading my Ardour 5.12 project. I'm using the latest master branch.

**Comment by davidhealey** [comment] 2020-04-20 00:16
Noise profiles still being reset with Ardour 6 release candidate.

**Comment by FrnchFrgg** [comment] 2020-04-20 14:25
@davidhealey I do not see that here. Noise Repellent correctly saves and restores the noise profile in my A6 projects. So either there is a problem with your setup, or a bad interaction from Noise Repellent with it. Maybe something was overlooked in the way NR stores its profiles, that makes it fail in your system.
Could you create a session that exhibits the problem and attach a zip file of it here ?

**Comment by davidhealey** [comment] 2020-04-20 19:52
I've narrowed down the issue. It only seems to happen if the track has more than 2 channels.


[Noise Repellent Test.zip](https://github.com/lucianodato/noise-repellent/files/4505821/Noise.Repellent.Test.zip)

**Comment by davidhealey** [comment] 2020-04-21 00:12
I just spoke with the Ardour devs and it seems this is an issue with Ardour assuming the state is shared for all instances of the plugin. When I add it to a three channel track it inserts 3 instances. The solution is to instead insert 3 copies of the plugin into the chain and route them so each one gets one channel of audio.

**Comment by lucianodato** [comment] 2020-06-27 00:54
yep, the plugin is mono
